version: '3.8'

services:

  postgres:
    image: postgres:14.2

    volumes:
      - pong_db:/var/lib/postgresql/data/

    networks:
      - netpong

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}

  back:
    build: ./_build/back
    depends_on:
      - postgres

    volumes:
      - ./api:/app

    networks:
      - netpong

    environment:
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_DB: ${DB_DB}

      JWT_SECRET: ${JWT_SECRET}

      API_AUTHORIZE: ${API_AUTHORIZE}
      API_REDIRECT_URL: ${API_REDIRECT_URL}
      API_UID: ${API_UID}
      API_SECRET: ${API_SECRET}

      GOOGLE_AUTH_APP_NAME: ${GOOGLE_AUTH_APP_NAME}

    working_dir: /app


  front:
    build: ./_build/front

    volumes:
      - ./site:/app

    networks:
      - netpong

    working_dir: /app


  nginx:
    build: ./_build/nginx
    depends_on:
      - front
      - back

    ports:
      - "8080:80"
      - "8443:443"

    volumes:
      - ./_build/nginx/certs:/certs

    networks:
      - netpong

networks:
  netpong:

volumes:
  pong_db: