version: '3'
services:
        nginx:
                image: nginx:stable
                env_file: .env
                restart: always
                networks: [arnatrans]
                ports: ["80:80"]
                depends_on: [njs]
        njs:
                image: nestjs/cli:286d7b9930ef05f7c32484b48b208233c5f44329
                env_file: .env
                restart: always
                networks: [arnatrans]
                ports: ["3000:3000"]
                depends_on: [db]

        db:
                image: postgres:12.13-alpine3.17
                env_file: .env
                restart: always
                networks: [arnatrans]
                ports: ["3306:3306"]
                volumes: [data:/var/lib/postgresql/data/pgdata]

networks:
        arnatrans:
                driver: bridge

volumes:
        data:
