
version: '3.8'

services:

  postgres:
    restart: "always"


  back:
    restart: "always"

    environment:
      BUILD_TYPE: "Production" 

  front:
    restart: "always"

    environment:
      BUILD_TYPE: "Production" 

  nginx:
    restart: "always"

    ports:
      - "8080:80"

