version: '3.8'

services:

  postgres:
    restart: "no"

    ports:
      - "5432:5432"


  adminer:
    image: mcaubrey/adminer
    depends_on:
      - postgres

    restart: "no"

    ports:
      - "8081:8080"

    environment:
      ADMINER_DEFAULT_SYSTEM: pgsql
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DATABASE: ${DB_DB}


  back:
    restart: "no"

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

    ports:
      - "4000:3000"

    volumes:
      - ./api:/app


  front:
    restart: "no"

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

    ports:
      - "3000:3000"

    volumes:
      - ./site:/app


  nginx:
    restart: "no"

