version: '3.8'

services:

  postgres:
    restart: "no"

    #ports:
    #  - "5432:5432"


  adminer:
    image: adminer
    # image: mcaubrey/adminer
    depends_on:
      - postgres

    restart: "no"

    ports:
      - "8081:8080"

    networks:
      - netpong


  chat:
    build: ./_build/chat-client

    restart: "no"

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

    # ports:
    #   - "3001:3001"

    networks:
      - netpong

    working_dir: /app


  back:
    restart: "no"

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

    # ports:
    #   - "4000:4000"


  front:
    restart: "no"

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

    ports:
      - "3000:3000"


  nginx:
    restart: "no"

